"""All Tables

Revision ID: 759cb9fbe22a
Revises: bb38be79c0d9
Create Date: 2024-03-14 10:37:45.471382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759cb9fbe22a'
down_revision = 'bb38be79c0d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_distances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regular_distance', sa.Integer(), nullable=False),
    sa.Column('max_distance', sa.Integer(), nullable=False),
    sa.Column('min_distance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club_distance_joins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('club_distance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_distance_id'], ['club_distances.id'], name=op.f('fk_club_distance_joins_club_distance_id_club_distances')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_distance_joins_club_id_clubs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_club_distance_joins_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_distance_joins')
    op.drop_table('clubs')
    op.drop_table('club_distances')
    # ### end Alembic commands ###
