"""update PastRound table

Revision ID: 9c080dc60989
Revises: ebec07ae82a3
Create Date: 2024-03-19 17:24:01.018046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c080dc60989'
down_revision = 'ebec07ae82a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_rounds', schema=None) as batch_op:
        batch_op.alter_column('green_in_regulation',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('putts',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_rounds', schema=None) as batch_op:
        batch_op.alter_column('putts',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('green_in_regulation',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
