"""new new migrate

Revision ID: a8e12413930e
Revises: 
Create Date: 2024-03-18 16:15:23.381887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e12413930e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_distances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regular_distance', sa.Integer(), nullable=False),
    sa.Column('max_distance', sa.Integer(), nullable=False),
    sa.Column('min_distance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('_password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('club_distance_joins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('club_distance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_distance_id'], ['club_distances.id'], name=op.f('fk_club_distance_joins_club_distance_id_club_distances')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_distance_joins_club_id_clubs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_club_distance_joins_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('past_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=8), nullable=False),
    sa.Column('course', sa.String(), nullable=False),
    sa.Column('par', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('fairway_hit', sa.String(), nullable=False),
    sa.Column('green_in_regulation', sa.String(), nullable=False),
    sa.Column('putts', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('average_score', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_past_rounds_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scorecards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=8), nullable=False),
    sa.Column('course', sa.String(), nullable=False),
    sa.Column('par', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('fairway_hit', sa.String(), nullable=False),
    sa.Column('green_in_regulation', sa.String(), nullable=False),
    sa.Column('putts', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_scorecards_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scorecards')
    op.drop_table('past_rounds')
    op.drop_table('club_distance_joins')
    op.drop_table('users')
    op.drop_table('clubs')
    op.drop_table('club_distances')
    # ### end Alembic commands ###
