"""update PastRound table

Revision ID: ebec07ae82a3
Revises: 9a3fecfb1877
Create Date: 2024-03-19 17:21:25.412098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebec07ae82a3'
down_revision = '9a3fecfb1877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_rounds', schema=None) as batch_op:
        batch_op.alter_column('fairway_hit',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_rounds', schema=None) as batch_op:
        batch_op.alter_column('fairway_hit',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
